<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <title>12-promise的几个关键问题5</title>
</head>
<body>
<script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    /*
        中断promise链：
            1.当使用promise的then链式调用时，在中间中断，不再调用后面的回调函数
            2.办法：在失败的回调函数中返回一个pending状态的Promise实例
    */
    function sendAjax(url, data) {
        return new Promise((resolve, reject) => {
            //实例xhr
            const xhr = new XMLHttpRequest();
            //绑定监听
            xhr.onreadystatechange = () => {
                if (xhr.readyState === 4) {
                    if (xhr.status >= 200 && xhr.status < 300) {
                        resolve(xhr.response);
                    } else {
                        reject('请求出错了');
                    }
                }
            }
            //整理参数
            let str = '';
            for (let key in data) {
                str += `${key}=${data[key]}&`;
            }
            str = str.slice(0, -1);

            xhr.open('GET', url + '?' + str);
            xhr.responseType = 'json';
            xhr.send();
        });
    }

    //发送第一次请求
    sendAjax('https://api.apiopen.top/getJoke', {page: 1})
        .then(
            value => {
                console.log('第1次请求成功了', value);
                //发送第二次请求
                return sendAjax('https://api.apiopen.top/getJoke2', {page: 1});
            },
            reason => {
                console.log('第1次请求失败了', reason);
                return new Promise(() => {});
            }
        )
        .then(
            value => {
                console.log('第2次请求成功了', value);
                //发送第三次请求
                return sendAjax('https://api.apiopen.top/getJoke', {page: 1});
            },
            reason => {
                console.log('第2次请求失败了', reason);
                return new Promise(() => {});
            }
        )
        .then(
            value => {
                console.log('第3次请求成功了', value);
            },
            reason => {
                console.log('第3次请求失败了', reason);
            }
        )


</script>
</body>
</html>